import { PrimitiveValue, Expression, AST } from "@yukigo/ast";
import { InterpreterError, InterpreterVisitor } from "./components/Visitor.js";
import { EnvBuilderVisitor } from "./components/EnvBuilder.js";

export type Bindings = [string, PrimitiveValue][];

export type LogicSearchMode = "first" | "all" | "stream";
export type InterpreterConfig = {
  lazyLoading?: boolean;
  debug?: boolean;
  queryMode?: LogicSearchMode;
};

export type Environment = Map<string, PrimitiveValue>;
export type EnvStack = Environment[];

const DefaultConfiguration: Required<InterpreterConfig> = {
  lazyLoading: false,
  debug: false,
  queryMode: "first",
};

/**
 * The Interpreter class is responsible for evaluating the Abstract Syntax Tree (AST)
 * generated by the parsers.
 *
 * It manages the global execution environment and delegates the actual evaluation
 * of Expression nodes to a dedicated visitor.
 */
export class Interpreter {
  private globalEnv: EnvStack;
  private readonly config: InterpreterConfig;

  /**
   * @param ast The Abstract Syntax Tree (AST) of the program to be interpreted.
   */
  constructor(ast: AST, config?: InterpreterConfig) {
    this.globalEnv = new EnvBuilderVisitor().build(ast);
    console.log(this.globalEnv);
    this.config = config ?? DefaultConfiguration;
  }

  /**
   * Evaluates a single Expression node within the context of the global environment.
   *
   * @param expr The root Expression node to be evaluated.
   * @returns The resulting primitive value (number, string, boolean, etc.) after evaluation.
   */
  public evaluate(expr: Expression): PrimitiveValue {
    try {
      const visitor = new InterpreterVisitor(this.globalEnv, this.config);
      const evaluatedExpr = visitor.visit(expr);
      return evaluatedExpr;
    } catch (error) {
      if (error instanceof InterpreterError) console.log(error.formatStack());
      throw error;
    }
  }
}
